server:
  port: 80

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/study
      username: root
      password: root

mybatis-plus:
  configuration:
    log-impl: org.


