
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root

  web:
    resources:
      static-locations: classpath:/static/,file:${photo.file.dir}

photo:
  file:
    dir: D:\Code-repository\IDEA\Java_Study_For_School_projects\Springboot\spring\home_0514\src\main\resources\static\upload

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml

server:
  port: 8081