server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  thymeleaf:
    cache: false
    mode: development
    prefix: classpath:/templates/  # 卡我半天
    suffix: .html

  web:
    resources:
      staticLocations: classpath:/static/, file:${photo.file.dir}

  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 100
        max-idle: 10
        min-idle: 2
        max-wait: 10000
    password:

photo:
  file:
    dir: D:\Code-repository\IDEA\Java_Study_For_School_projects\Springboot\spring\home_0511\src\main\resources\upload

mybatis-plus:
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/**/*.xml


