server:
  port: 80

spring:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: root
  thymeleaf:
    cache: false
    mode: development
    prefix: /templates
    suffix: .html

  web:
    resources:
      staticLocations: classpath:/static/, file:${photo.file.dir}


photo:
  file:
    dir: D:/Code-repository/IDEA/Java_Study_For_School_projects/Springboot/spring/home_0428/src/main/resources/upload

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/**/*.xml
